apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: metrics-app
spec:
  applicationImage: <プロジェクト名>/<イメージ・ストリーム名>:<タグ>
  applicationName: metrics-app
  env:
  - name: WLP_LOGGING_MESSAGE_FORMAT
    value: json
  - name: WLP_LOGGING_MESSAGE_SOURCE
    value: message,trace,accessLog,ffdc,audit
  expose: true
  monitoring: {}
