apiVersion: v1
kind: ConfigMap
metadata:
  name: liberty-env-config
data:
  server.env: |-
    WLP_LOGGING_CONSOLE_FORMAT=json
    WLP_LOGGING_CONSOLE_LOGLEVEL=info
    WLP_LOGGING_CONSOLE_SOURCE=message,trace,accessLog,ffdc
