apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: liberty-pvc
 labels:
   <ストレージクラスに合わせて設定>
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 20Gi
 storageClassName: <利用したいストレージクラスを指定>
