apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: liberty-db2-session
  labels:
    name: liberty-db2-session
spec:
  applicationImage: <プロジェクト名>/<イメージ・ストリーム名>:<タグ>
  env:
    - name: WLP_LOGGING_MESSAGE_FORMAT
      value: "json"
    - name: WLP_LOGGING_MESSAGE_SOURCE
      value: "message,trace,accessLog,ffdc,audit"
  replicas: 2
  expose: true
