apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: mount-ibm-file-storage
  name: mount-ibm-file-storage
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: permissionsfix
        image: registry.access.redhat.com/ubi8/ubi:latest
        command: ["/bin/sh", "-c"]
        args:
          - chown 1001:1001 /mount;
        securityContext:
          privileged: true
        volumeMounts:
        - name: dump-volume
          mountPath: /mount
      volumes:
      - name: dump-volume
        persistentVolumeClaim:
          claimName: liberty-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccountName: batch
      terminationGracePeriodSeconds: 30
