apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: cart
spec:
  applicationImage: <イメージ名>
  applicationName: cart
  expose: true
  pullPolicy: Always
  replicas: 1
  service:
    port: 9080
    type: ClusterIP
  env:
  - name: USER_NAME
    valueFrom:
      secretKeyRef:
        name: secret-infinispan-auth
        key: username
  - name: USER_PASSWD
    valueFrom:
      secretKeyRef:
        name: secret-infinispan-auth
        key: password
  - name: SRV_HOST
    valueFrom:
      secretKeyRef:
        name: secret-infinispan-auth
        key: srv_host
  - name: SRV_PORT
    valueFrom:
      secretKeyRef:
        name: secret-infinispan-auth
        key: srv_port
