apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: sample-app
  labels:
    name: sample-app
spec:
  applicationImage: <プロジェクト名>/<イメージ・ストリーム名>:<タグ>
  env:
    - name: WLP_LOGGING_MESSAGE_FORMAT
      value: "json"
    - name: WLP_LOGGING_MESSAGE_SOURCE
      value: "message,trace,accessLog,ffdc,audit"
  expose: true
